on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Verify Code

jobs:
  fmt-lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: cargo fmt
        run: cargo fmt --all -- --check
      - name: cargo clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - name: cargo build
        run: cargo build
      - name: cargo test
        run: cargo test

